dist: xenial
sudo: required

language: python
python:
- 3.6
- 3.7
- 3.8

os:
- linux
- osx
- windows

install:
- pip install tox-travis
script:
- tox

stages:
- lint
- test
- deploy

jobs:
  allow_failures:
  - env: TOXENV=bandit
  - os: osx
  - os: windows
  include:
  - { stage: lint, python: 3.8, env: TOXENV=flake8 }
  - { stage: lint, python: 3.8, env: TOXENV=pylint }
  - { stage: lint, python: 3.8, env: TOXENV=bandit }
  - { stage: lint, python: 3.8, env: TOXENV=readme }

  - stage: deploy
    install: skip
    script: skip
    deploy:
      provider: pypi
      distributions: sdist bdist_wheel
      user: bittner
      password:
        secure: hhyaxP28sn3iHe6CPAgrXeK3cOm4+jPdu4Q6K9J6eimVwGVx0C+a47TLzZ6CtSixmgyY5oByLU9Hb5lHCbAkJA9SqYGBJr1xQB/mb4fiLh0O5YjXNpJ1cV13buhobC2DoIXoBbbSYn7Axul/ZmmYGfOUFHjdGudsfllG6xq6ZTA75zerO/l+NWAA3jEjBIm4v2fRfsBJFe+ro/FMoT1zbagD6t4xK6YruHoy7zUjReKtpXFvH+2ifTPeW+KBNUN+p9h8QMlVAJBRvjQ1CwwrZq8Xh23HwyyQaaK8lI4yHIvyIdKPB9lBR+fbA30qT55jMnBCYfq+wJ71moc3MzozhR+NxpB9YeqVgciXJrlqs92ipFj6JYqZVXveBWifm2/Dy5y+pqjJNjF0Pt8WmTtICeHzJ+K9E39pNLvjkaOFTBQclsN2NpnaUSe4W8i/gnMLTfJWJN+Y7iVlH4P0/ed3ymKwsgkYl9NHMPa+RGFBCizdKYW08pZ7LLVpWQ+ItpKHUPjvp0keCodb6sIX+9W2p7lmTXT1jqcvyqUvBHqkyOLZFRHktb/YF+IDJGRYYMAqhAsD36L8b6plaveVHd8yQCPVoJbIapmcwrJlJiCXq3to9KCXhDoMnrpxk7d+eth8K+wLh/Wc2UWPbw9pqlwa+f+kP0ySIQI19RCXz51NtBU=
      on:
        tags: true
