[tool.bandit]
exclude = [".tox","build","dist","tests"]

[tool.black]
color = true

[tool.coverage.xml]
output = "tests/coverage-report.xml"

[tool.isort]
color_output = true
profile = "black"

[tool.pylint.master]
output-format = "colorized"

[tool.pytest.ini_options]
addopts = "--junitxml=tests/unittests-report.xml --doctest-modules --color=yes --verbose"
